id: DCF7F5566
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:10:02+00:00'
last_modified: '2022-05-27T05:41:07.651413+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    bbdf:
      image_group_id: I1PD95902
      title: རྩོད་པ་བཟློག་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      order: 57
      base_file: bbdf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
