id: 09a154e0ca3f43a7aa35e5f513eb457c
initial_creation_type: ocr
source_metadata:
  volumes:
    970e1e475aa640e3a81180f43a6d9cec:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
